---
# Source: eth2-prysm/templates/beacon-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: beacon-service
  namespace: prysm
spec:
  selector:
    app: beacon
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
