---
# Source: eth2-prysm/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: beacon
  namespace: prysm
---
# Source: eth2-prysm/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: validator-client
  namespace: prysm
---
# Source: eth2-prysm/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prysm
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
---
# Source: eth2-prysm/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prysm-cluster-role-binding
roleRef:
  kind: ClusterRole
  name: prysm
  apiGroup: rbac.authorization.k8s.io
subjects:
# Authorize specific service accounts:
- kind: ServiceAccount
  name: beacon
  namespace: prysm
- kind: ServiceAccount
  name: validator-client
  namespace: prysm
