# Default values for eth2-nimbus.
# This is a YAML-formatted file.

# Kubernetes namespace for Nimbus client deployments.
namespace: nimbus

# Specify which Ethereum 2.0 testnet to use. If the target network is mainnet, leave this field blank.
ethereumTestnet: prater

# A required field that determines the persistent storage type. Default to hostPath.
# Available options: nfs and hostPath.
persistentVolumeType: "nfs"

# NFS configurations. Only need to fill this section when persistentVolumeType is set to "nfs".
nfs:
  # IP address of the NFS server.
  serverIp: 172.20.10.10
  # The user ID will be used to run all processes in the container. The user should have the access to the mounted NFS volume.
  # All directories and files created with the processes are owned by this user.
  user: 1001
  # The group ID will be used to run all processes in the container. The group should have the access to the mounted NFS volume.
  # If this field is not set, the group ID of the processes will be 0, which means they will have root access.
  # See https://kubernetes.io/docs/tasks/configure-pod-container/security-context/ for more info.
  #
  # All directories and files created with the processes are owned by this group.
  group: 2000

# A required section that configures image registry, image name and version tag for Nimbus client.
# Nimbus currently pushes images to:
#   Docker Hub: https://hub.docker.com/r/statusim/nimbus-eth2
image:
  # The image name of the Nimbus client:
  #   Docker Hub: index.docker.io/statusim/nimbus-eth2
  nimbusImage: index.docker.io/statusim/nimbus-eth2
  # Nimbus release version. 
  # Check https://github.com/status-im/nimbus-eth2/releases for release info. 
  versionTag: amd64-v1.2.1

# A required section that contains Nimbus client information.
nimbus:
  # This field determines how long it will wait before the Nimbus client starts or restarts.
  # It's a way to protect the validator client from double attesting or block proposing when the DB is out-of-date.
  startWaitTime: 780
  # A required section that contains information for all Nimbus clients
  clients:
    # This section contains information for one Nimbus client.
    # "client1" is the name of this Nimbus client section. You can change it to other strings as long as it's different than other section names.
    client1:
      # This field specifies the name and label for Nimbus client deployment and container.
      name: nimbus-1
      # Main Ethereum 1 node endpoint.
      web3Provider: http://127.0.0.1:8545
      # A list of Ethereum 1 node fallback endpoints. 
      # When the main endpoint isn't available, Nimbus will use these fallback endpoints instead until the main endpoint becomes available again.
      fallbackWeb3Providers:
        - http://127.0.0.1:8546
        - http://127.0.0.1:8547
      # UDP Port opened for P2P connection with the beacon node.
      # See https://nimbus.guide/options.html for more info.
      p2pUdpPort: 9000
      # TCP Port opened for P2P connection with the beacon node.
      # See https://nimbus.guide/options.html for more info.
      p2pTcpPort: 9000
      # The volume path of the directory where Nimbus will store all blockchain data.
      # If persistentVolumeType is set to "nfs", this variable represents the data volume path on NFS.
      # If the type is set to "hostPath", it represents the volume path on the host node.
      dataVolumePath: /data/nimbus/beacon-1
      # The volume path of validator keystores. 
      # It's recommended to have different value for each Nimbus client to avoid using the wrong Nimbus client data.
      validatorsVolumePath: /data/nimbus/validators-1
      # The volume path of the validator keystores passwords. 
      # It's recommended to have different value for each Nimbus client to avoid using the wrong wallet.
      secretsVolumePath: /data/nimbus/secrets-1
      # A mark you want to leave each time the Nimbus client proposes a block.
      # It can be a message or a pixel (on the graffiti wall).
      # See https://beaconcha.in/charts/graffiti_wordcloud for example.
      graffiti: "eth2 x k8s"
    client2:
      # This field specifies the name and label for Nimbus client deployment and container.
      name: nimbus-2
      web3Provider: http://127.0.0.1:8545
      fallbackWeb3Providers:
      p2pUdpPort: 8000
      p2pTcpPort: 8000
      dataVolumePath: /data/nimbus/beacon-2
      validatorsVolumePath: /data/nimbus/validators-2
      secretsVolumePath: /data/nimbus/secrets-2
      graffiti: "eth2 x k8s"
    
  # You can add more nimbus clients below. The name of a new Nimbus client section can be client3 or anything else that you prefer
  # as long as the section has the same indentation as other Nimbus client sections and contains all the fields under the section name.
  # client3:
  #   name:
  #   web3Provider:
  #   fallbackWeb3Providers:
  #   p2pUdpPort:
  #   p2pTcpPort:
  #   dataVolumePath: 
  #   validatorsVolumePath:
  #   secretsVolumePath:
  #   graffiti:
