{{- with .Values.beacon }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ .name }}
spec:
  selector:
    matchLabels:
      app: {{ .name }}
  replicas: 1
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
      - name: {{ .name }}
        {{- with $.Values.image }}
        image: "{{ .beaconImage }}:{{ .version }}"
        {{- end }}
        args:
        {{- if $.Values.ethereumTestnet }}
        - --{{ $.Values.ethereumTestnet }}
        {{- end}}
        - --rpc-host=0.0.0.0
        - --p2p-tcp-port={{ .p2pTcpPort }}
        - --p2p-udp-port={{ .p2pUdpPort }}
        - --http-web3provider={{ .web3Provider }}
        {{- range .fallbackWeb3Providers }}
        - --fallback-web3provider={{ . }}
        {{- end }}
        - --datadir=/data/prysm/beacon
        - --accept-terms-of-use
        ports:
        - containerPort: {{ .p2pTcpPort }}
          hostPort: {{ .p2pTcpPort }}
          protocol: TCP
        - containerPort: {{ .p2pUdpPort }}
          hostPort: {{ .p2pUdpPort }}
          protocol: UDP
        - containerPort: 4000
          protocol: TCP
          hostPort: 4000
        volumeMounts:
        - name: beacon-storage
          mountPath: /data/prysm/beacon
      volumes:
      - name: beacon-storage
        {{- if $.Values.nfsEnabled }}
        nfs:
          path: {{ .dataVolumePath }}
          server: {{ $.Values.nfsServerIp }}
          readOnly: false
        {{- else}}
        hostPath:
          path: {{ .dataVolumePath }}
        {{- end}}
      {{- if $.Values.nfsEnabled }}
      securityContext:
        runAsUser: {{ $.Values.nfsUser }}
        runAsGroup: {{ $.Values.nfsGroup }} 
      {{- end}}
      serviceAccountName: beacon
      restartPolicy: Always
{{- end }}