{{- range $key, $nimbusClient := .Values.nimbus.clients }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $validatorClient.name }}
  namespace: nimbus
  labels:
    app: {{ $validatorClient.name }}
spec:
  selector:
    matchLabels:
      app: {{ $validatorClient.name }}
  replicas: 1
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ $validatorClient.name }}
    spec:
      initContainers:
      - name: init-wait
        image: alpine:3.13.2
        command: ['sh', '-c', 'echo Wait for {{ $.Values.validatorStartWaitTime }} seconds for extra slashing protection! && sleep {{ $.Values.validatorStartWaitTime }}']
      containers:
      - name: nimbus
        image: "{{ $.Values.image.nimbusImage }}:{{ $.Values.image.versionTag }}"
        args:
        {{- if $.Values.ethereumTestnet }}
        - --network={{ $.Values.ethereumTestnet }}
        {{- end }}
        - --non-interactive
        - --tcp-port={{ $validatorClient.p2pTcpPort }}
        - --udp-port={{ $validatorClient.p2pUdpPort }}
        - --data-dir=/data/nimbus/beacon
        - --validators-dir=/data/nimbus/validators
        - --secrets-dir=/data/nimbus/secrets
        - --web3-url={{ $validatorClient.web3Provider }}
        - --graffiti={{ $validatorClient.graffiti | quote }}
        ports:
        - containerPort: {{ $validatorClients.p2pTcpPort }}
          hostPort: {{ $validatorClient.p2pTcpPort }}
          protocol: TCP
        - containerPort: {{ $validatorClient.p2pUdpPort }}
          hostPort: {{ $validatorClient.p2pUdpPort }}
          protocol: UDP
        volumeMounts:
        - name: nimbus-beacon-storage
          mountPath: /data/nimbus/beacon
          readOnly: false
        - name: nimbus-validators-storage
          mountPath: /data/nimbus/validators
          readOnly: false
        - name: nimbus-secrets-storage
          mountPath: /data/nimbus/secrets
          readOnly: true
      volumes:
      {{- if eq $.Values.persistentVolumeType "nfs" }}
      - name: nimbus-beacon-storage
        nfs:
          path: {{ $validatorClient.dataVolumePath }}
          server: {{ $.Values.nfs.serverIp }}
          readOnly: false
      - name: nimbus-validators-storage
        nfs:
          path: {{ $validatorClient.validatorsVolumePath }}
          server: {{ $.Values.nfs.serverIp }}
          readOnly: false
      - name: nimbus-secrets-storage
        nfs:
          path: {{ $validatorClient.secretsVolumePath }}
          server: {{ $.Values.nfs.serverIp }}
          readOnly: true
      {{- else }}
      - name: nimbus-beacon-storage
        hostPath:
          path: {{ $validatorClient.dataVolumePath }}
      - name: nimbus-validator-storage
        hostPath:
          path: {{ $validatorClient.validatorsVolumePath }}
      - name: nimbus-secret-storage
        hostPath:
          path: {{ $validatorClient.secretsVolumePath }}
      {{- end }}
      securityContext:
        runAsUser: {{ $.Values.nfs.user }}
        runAsGroup: {{ $.Values.nfs.group }}
      serviceAccountName: nimbus
      restartPolicy: Always

---
{{- end }}
