apiVersion: apps/v1
kind: Deployment
metadata:
  name: beacon
  namespace: lighthouse
  labels:
    app: beacon
spec:
  selector:
    matchLabels:
      app: beacon
  replicas: 1
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: beacon
    spec:
      containers:
      - name: beacon
        image: index.docker.io/sigp/lighthouse:v1.3.0
        args:
        - lighthouse
        - --network=prater
        - bn
        - --staking
        - --http-address=0.0.0.0
        - --eth1-endpoints=<goerli eth1 node>
        - --datadir=/data/lighthouse/beacon
        ports:
        - containerPort: 9000
          hostPort: 9000
          protocol: TCP
        - containerPort: 9000
          hostPort: 9000
          protocol: UDP
        - containerPort: 5052
          protocol: TCP
        volumeMounts:
        - name: beacon-storage
          mountPath: /data/lighthouse/beacon
      volumes:
      - name: beacon-storage
        hostPath:
          path: /data/lighthouse/beacon
      serviceAccountName: beacon
      restartPolicy: Always
