---
# Source: eth2-lighthouse/templates/beacon-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: beacon-service
  namespace: lighthouse
spec:
  selector:
    app: beacon
  ports:
    - protocol: TCP
      port: 5052
      targetPort: 5052
