# Default values for eth2prysm.
# This is a YAML-formatted file.

namespace: prysm
imageVersion: v1.3.3

ethereumTestnet: pyrmont

beacon:
  name: beacon
  dataHostPath: /data/prysm/beacon
  web3provider: http://127.0.0.1:8545
  p2pUdpPort: 12000
  p2pTcpPort: 13000

validator:
  name: validator
  startWaitTime: 780
  dataHostPath: /data/prysm/validator
  graffiti: "eth2 x k8s"
  walletHostPath: /data/prysm/wallet
  walletPassword: "example-password"
