kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  # add a mount from /path/to/my/files on the host to /files on the node
  extraMounts:
  - hostPath: /data/prysm/beacon
    containerPath: /data/prysm/beacon
  - hostPath: /data/prysm/validator-client-1
    containerPath: /data/prysm/validator-client-1
  - hostPath: /data/prysm/wallet-1
    containerPath: /data/prysm/wallet-1
