{{- with .Values.beacon }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ .name }}
spec:
  selector:
    matchLabels:
      app: {{ .name }}
  replicas: 1
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
      - name: {{ .name }}
        image: "{{ $.Values.image.beaconImage }}:{{ $.Values.image.versionTag }}"
        args:
        {{- if $.Values.ethereumTestnet }}
        - --network={{ $.Values.ethereumTestnet }}
        {{- end }}
        - --p2p-port={{ .p2pPort }}
        - --rest-api-enabled
        - --rest-api-host-allowlist={{ $.Values.beacon.name }}-service.{{ $.Values.namespace }}.svc.cluster.local
        - --eth1-endpoints={{ .eth1Endpoints | join "," }}
        - --data-beacon-path=/data/teku/beacon
        - --log-destination=CONSOLE
        ports:
        - containerPort: {{ .p2pPort }}
          hostPort: {{ .p2pPort }}
          protocol: TCP
        - containerPort: {{ .p2pPort }}
          hostPort: {{ .p2pPort }}
          protocol: UDP
        - containerPort: 5051
          protocol: TCP
        volumeMounts:
        - name: beacon-storage
          mountPath: /data/teku/beacon
      volumes:
      - name: beacon-storage
        {{- if eq $.Values.persistentVolumeType "nfs" }}
        nfs:
          path: {{ .dataDirPath }}
          server: {{ $.Values.nfs.serverIp }}
          readOnly: false
        {{- else }}
        hostPath:
          path: {{ .dataDirPath }}
        {{- end }}
      securityContext:
        {{- toYaml $.Values.securityContext | nindent 8 }}
      serviceAccountName: beacon
      restartPolicy: Always
{{- end }}
