{{- with .Values.beacon }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ .name }}
spec:
  selector:
    matchLabels:
      app: {{ .name }}
  replicas: 1
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
      - name: {{ .name }}
        image: "{{ $.Values.image.beaconImage }}:{{ $.Values.image.versionTag }}"
        args:
        {{- if $.Values.ethereumTestnet }}
        - --{{ $.Values.ethereumTestnet }}
        {{- end }}
        - --rpc-host=0.0.0.0
        - --monitoring-host=0.0.0.0
        - --p2p-tcp-port={{ .p2pTcpPort }}
        - --p2p-udp-port={{ .p2pUdpPort }}
        - --http-web3provider={{ first (required "At least one eth1 endpoint is required." .eth1Endpoints) }}
        {{- range rest .eth1Endpoints }}
        - --fallback-web3provider={{ . }}
        {{- end }}
        - --datadir=/data/prysm/beacon
        {{- if .genesisStateFile }}
        - --genesis-state={{ .genesisStateFile }}
        {{- end}}
        - --accept-terms-of-use
        ports:
        - containerPort: {{ .p2pTcpPort }}
          hostPort: {{ .p2pTcpPort }}
          protocol: TCP
        - containerPort: {{ .p2pUdpPort }}
          hostPort: {{ .p2pUdpPort }}
          protocol: UDP
        - containerPort: 4000
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
          name: metrics
        volumeMounts:
        - name: beacon-storage
          mountPath: /data/prysm/beacon
        livenessProbe:
          httpGet:
            path: /healthz
            port: metrics
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 60
          failureThreshold: 60 # beacon will restart every hour until it is fully synced
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /healthz
            port: metrics
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 60
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 1
      volumes:
      - name: beacon-storage
        {{- if eq $.Values.persistentVolumeType "nfs" }}
        nfs:
          path: {{ .dataDirPath }}
          server: {{ $.Values.nfs.serverIp }}
          readOnly: false
        {{- else }}
        hostPath:
          path: {{ .dataDirPath }}
        {{- end }}
      securityContext:
        {{- toYaml $.Values.securityContext | nindent 8 }}
      serviceAccountName: beacon
      restartPolicy: Always
{{- end }}
