apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.beacon.name }}-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.beacon.name }}
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
