apiVersion: v1
kind: ServiceAccount
metadata:
  name: beacon
  namespace: {{ .Values.namespace }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: validator-client
  namespace: {{ .Values.namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prysm
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prysm-cluster-role-binding
roleRef:
  kind: ClusterRole
  name: prysm
  apiGroup: rbac.authorization.k8s.io
subjects:
# Authorize specific service accounts:
- kind: ServiceAccount
  name: beacon
  namespace: {{ .Values.namespace }}
- kind: ServiceAccount
  name: validator-client
  namespace: {{ .Values.namespace }}
