{{- range $key, $validatorClient := .Values.validatorClients }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $validatorClient.name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ $validatorClient.name }}
spec:
  selector:
    matchLabels:
      app: {{ $validatorClient.name }}
  replicas: 1
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ $validatorClient.name }}
      annotations:
        checksum/config: {{ $validatorClient.walletPassword | sha256sum }}
    spec:
      initContainers:
      - name: init-wait
        image: alpine:3.13.2
        command: ['sh', '-c', 'echo "Wait for {{ $.Values.validatorStartWaitTime }} second(s) for extra slashing protection!" && sleep {{ $.Values.validatorStartWaitTime }}']
      containers:
      - name: {{ $validatorClient.name }}
        image: "{{ $.Values.image.validatorImage }}:{{ $.Values.image.version }}"
        args:
        {{- if $.Values.ethereumTestnet }}
        - --{{ $.Values.ethereumTestnet }}
        {{- end }}
        - --beacon-rpc-provider={{ $.Values.beacon.name }}-service.{{ $.Values.namespace }}.svc.cluster.local:4000
        - --datadir=/data/prysm/validator-client
        - --wallet-dir=/data/prysm/wallet
        - --wallet-password-file=/data/prysm/password/wallet-pwd.txt
        - --graffiti={{ $validatorClient.graffiti | quote }}
        - --accept-terms-of-use
        volumeMounts:
        - name: validator-client-storage
          mountPath: /data/prysm/validator-client
          readOnly: false
        - name: wallet-storage
          mountPath: /data/prysm/wallet
          readOnly: false
        - name: wallet-password
          mountPath: /data/prysm/password
          readOnly: true
      volumes:
      {{- if eq $.Values.persistentVolumeType "nfs" }}
      - name: validator-client-storage
        nfs:
          path: {{ $validatorClient.dataVolumePath }}
          server: {{ $.Values.nfs.serverIp }}
          readOnly: false
      - name: wallet-storage
        nfs:
          path: {{ $validatorClient.walletVolumePath }}
          server: {{ $.Values.nfs.serverIp }}
          readOnly: false
      {{- else }}
      - name: validator-client-storage
        hostPath:
          path: {{ $validatorClient.dataVolumePath }}
      - name: wallet-storage
        hostPath:
          path: {{ $validatorClient.walletVolumePath }}
      {{- end }}
      - name: wallet-password
        secret:
          secretName: {{ $validatorClient.walletPasswordSecretName }}
          items:
          - key: password
            path: wallet-pwd.txt
      securityContext:
        {{- toYaml $.Values.securityContext | nindent 8 }}
      serviceAccountName: validator-client
      restartPolicy: Always

---
{{- end }}
