{{- range $key, $validatorClient := .Values.validatorClients }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $validatorClient.walletPasswordSecretName }}
  namespace: {{ $.Values.namespace }}
type: Opaque
stringData:
  password: {{ $validatorClient.walletPassword }}

---
{{- end }}
