apiVersion: apps/v1
kind: Deployment
metadata:
  name: validator-client-1
  namespace: prysm
  labels:
    app: validator-client-1
spec:
  selector:
    matchLabels:
      app: validator-client-1
  replicas: 1
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: validator-client-1
    spec:
      initContainers:
      - name: init-wait
        image: alpine:3.13.2
        command: ['sh', '-c', 'echo Wait for 780 seconds for extra slashing protection! && sleep 780']
      containers:
      - name: validator-client-1
        image: gcr.io/prysmaticlabs/prysm/validator:v1.3.8
        args:
        - --prater 
        - --beacon-rpc-provider=beacon-service.prysm.svc.cluster.local:4000
        - --datadir=/data/prysm/validator-client-1
        - --wallet-dir=/data/prysm/wallet-1
        - --wallet-password-file=/data/prysm/password/wallet_pwd.txt
        - --graffiti="eth2 x k8s"
        - --accept-terms-of-use
        volumeMounts:
        - name: validator-storage
          mountPath: /data/prysm/validator-client-1
          readOnly: false
        - name: wallet-storage
          mountPath: /data/prysm/wallet-1
          readOnly: false
        - name: wallet-password
          mountPath: /data/prysm/password
          readOnly: true
      volumes:
      - name: validator-storage
        nfs:
          path: /data/prysm/validator-client-1
          server: 172.20.10.10
          readOnly: false
      - name: wallet-storage
        nfs:
          path: /data/prysm/wallet-1
          server: 172.20.10.10
          readOnly: false
      - name: wallet-password
        secret:
          secretName: wallet-password-1
          items:
          - key: password
            path: wallet_pwd.txt
      securityContext:
        runAsUser: 1001
        runAsGroup: 2000
      serviceAccountName: validator-client
      restartPolicy: Always
