name: Generate k8s yamls

on:
  push:
    branches:
      - github-action-helm  # Set a branch to deploy

jobs:
  yaml-generation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target branch
        uses: actions/checkout@v2 # https://github.com/actions/checkout
        with:
          ref: 'github-action-helm'

      - name: Generate Prysm yamls
        run: |
          for fullfile in ./prysm/helm/values-files/* 
            do
            filename="${fullfile##*/}"               # Remove path.
            foldername="${filename%.*}"              # Remove file extension.
            foldername="${foldername##*values-}"     # Remove 'values-' string.
            helm template ./prysm/helm -f $fullfile --output-dir ./prysm/temp/$foldername
          done

      - name: Move Prysm yamls
        run: |
          for tempdir in ./prysm/temp/*
            do
            dir=./prysm/"${tempdir##*/}"             # Remove path.
            if [ ! -d "$dir" ]; then mkdir $dir; fi  # Create yaml folder if it doesn't exist.
            mv $tempdir/eth2-prysm/templates/* $dir  # Move yamls to the correct folder.
          done
          rm -rf ./prysm/temp

      - name: Push Changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -am 'Generate k8s yamls with eth2 client Helm Charts.'
          git push