name: Automatically generate k8s yamls

on:
  push:
    branches:
      - github-action-helm # Set a branch

jobs:
  yaml-generation:
    runs-on: ubuntu-latest
    env:
      CLIENTS: "prysm,lighthouse,teku,nimbus"
    steps:
      - name: Checkout target branch
        uses: actions/checkout@v2 # https://github.com/actions/checkout
        with:
          ref: 'github-action-helm'

      - name: Generate yamls for Ethereum 2.0 clients
        run: |
          IFS="," read -ra CLIENTS <<< "$CLIENTS"
          for client in "${CLIENTS[@]}"
            do
            for fullfile in ./$client/helm/values-files/* 
              do
              filename="${fullfile##*/}"               # Remove path.
              foldername="${filename%.*}"              # Remove file extension.
              foldername="${foldername##*values-}"     # Remove 'values-' string.
              helm template ./$client/helm -f $fullfile --output-dir ./$client/temp/$foldername
            done
          done

      - name: Rearrange the locations for yaml files.
        run: |
          IFS="," read -ra CLIENTS <<< "$CLIENTS"
          for client in "${CLIENTS[@]}"
            do
            for tempdir in ./$client/temp/*
              do
              dir=./$client/"${tempdir##*/}"             # Remove path.
              if [ ! -d "$dir" ]; then mkdir $dir; fi  # Create yaml folder if it doesn't exist.
              mv $tempdir/eth2-$client/templates/* $dir  # Move yamls to the correct folder.
            done
            rm -rf ./$client/temp
          done

      - name: Push Changes
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # git checkout -b github-action-helm
          # git add -A
          # git commit -am 'Automatically generate k8s yamls with eth2 client Helm Charts.'
          # git push
          gh pr create --fill
